config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  devise_for :users
  
  root 'pages#home'
  get  '/help',    to: 'pages#help' 
  get  '/about',   to: 'pages#about'
  get  '/contact', to: 'pages#contact'
  get  '/signup',  to: 'users#new'
  get  '/users/:id', to: 'users#show', as: 'user'
  get  '/users', to: 'users#index'
  get  '/terms/show'# 登録前の注意事項
  get  '/users/:id/following_posts',to: 'users#following_posts' # フォローの投稿
  post '/follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post '/unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

  resources :notifications, only: :index
  resources :users do
    member do
     get :following, :followers, :following_posts
    end
  end
  resources :relationships,       only: [:create, :destroy]
  
  resources :posts, only: %i(new create index show destroy) do
  resources :photos, only: %i(create)
  resources :users, only: :show
  resources :likes, only: %i(create destroy)
  resources :comments, only: %i(create destroy)
  resources :password_resets, only: [:new, :create, :edit, :update]
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attr_accessor :remember_token, :activation_token, :reset_token
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :likes
  has_many :comments
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :posts, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable,:validatable, :omniauthable
  
  before_save { self.email = email.downcase }       
  validates :name,  presence: true, length: { maximum: 50 }
  validates :username,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },  
             format: { with: VALID_EMAIL_REGEX },
             uniqueness: { case_sensitive: false }
  validates :introduction,  presence: false, length: { maximum: 200 }    
  validates :website,  presence: false, length: { maximum: 200 } 
  validates :sex,  presence: false, length: { maximum: 10 }
  validates :phone,  presence: false, length: { maximum: 20 }
  
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
             
             
end           
         
  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first
    
    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        name:  auth.info.name,
        password: Devise.friendly_token[0, 20],
        image:  auth.info.image
      )
    end

    user
  end

 # アカウントを有効にする
  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest,  User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  private

    # メールアドレスをすべて小文字にする
    def downcase_email
      self.email = email.downcase
    end

    # 有効化トークンとダイジェストを作成および代入する
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
  

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end
  
end
  
  # before_actio n:configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :updatec]
  before_action :correct_user,   only: [:edit, :update]



  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update,:following,:follwer]



  def index
    @users = User.all
  end

  def following_posts
   @user  = User.find(params[:id])
   @users = @user.followings
      @posts = Post.limit(42).includes(:photos, :user).order('created_at DESC')
  end

  def new
  end
  
  
  def show
    @user = User.find(params[:id])
  end
  
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end


  def following_posts
    @user  = User.find(params[:id])
    @users = @user.followings
    @posts = Post.limit(30).includes(:photos, :user).order('created_at DESC')
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

  def current_user?(user)
     user == current_user
     
  end

app/views/users/_follow.html.erb
 <%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
  <div><%= f.hidden_field :following_id %></div>
  <%= f.submit "フォローする", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
 <% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>  

app/views/users/_stats.html.erb
 <% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
  <%= f.submit "フォロー中", class: "btn btn-large btn-secondary follow-btn" %>
<% end %>

app/views/users/following_posts.html.erb
<div class="center">
<h1>友達の写真をチェックしよう</h1>
<div class="row">
<%  @users.each do |user| %>
<% @posts.each do |post| %>
 <div class="col-md-4" >
 <div>
 <h6><%= post.caption %></h6>
 <%= link_to post_path(post) do %>
  <%= image_tag post.photos.first.image.url(:medium) %>
<% end %>
</div>
</div>
<% end %>
<% end %>
</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>


<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

<% if user_signed_in? %>
  <p><%= link_to "マイページへ", user_path(current_user),class: "btn btn-primary" %></p>

<% end %>

app/views/users/new.js.erb
$('#samplRemote')
. <%= link_to 'フォロー外す', unfollow_path(user.id),method: :POST, remote: true,class: "btn btn-secondary" %>
$('#samplRemote')
 <%= link_to 'フォローする', follow_path(user.id),method: :POST, remote: true, class: "btn btn-primary" %>

app/views/users/show.html.erb
<div class="profile-wrap">
  <div class="row">
    <div class="col-md-4 text-center">
      <%= image_tag avatar_url(@user), class: "round-img" %>
    </div>
    <div class="col-md-8">
      <div class="row">
        <uL>
        <li><h3><%= @user.name %></h3></li>
        <li>ユーザー名: <%= @user.username %></li>
        <li>Website：<%= @user.website %></li>
        <li>投稿数：<%= @user.posts.count %></li>
        <li>自己紹介：<%= @user.introduction %></li>
        </ul>
        <% if @user == current_user %>
       <%= link_to "プロフィールを編集", edit_user_registration_path, class: "btn btn-outline-dark common-btn edit-profile-btn" %>
        <button type="button" class="setting" data-toggle="modal" data-target="#exampleModal"></button>
        </div>
      <% end %>
    
　　　<%= render 'stats' %>
　　　<%= render 'follow_form' %>
　　

        </div>
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">設定</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
                
              </div>
              <div class="list-group text-center">
                <%= link_to "サインアウト", destroy_user_session_path, method: :delete, class: "list-group-item list-group-item-action" %>
                <%= link_to "キャンセル", "#", class: "list-group-item list-group-item-action", "data-dismiss": "modal" %>
                
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>


<div class ="center">
<div class="row">
<%  @user.posts.each do |post| %>

 <div class="col-md-4" >
 <div>
 <h6><%= post.caption %></h6>
 <%= link_to post_path(post) do %>
  <%= image_tag post.photos.first.image.url(:medium) %>
<% end %>
</div>
</div>
<% end %>
</div>

app/views/users/show_follow.html.erb
<% @user.followings.each do |user| %>
<table>
<ul class="users">
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
    </li>
</ul>
</table>
<% end %>

app/views/users/show_follower.html.erb
 <% @user.followers.each do |user| %>
<table>
<ul class="users">
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
    </li>
</ul>
</table>
<% end %>