config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  devise_for :users
  
  root 'pages#home'
  get  '/help',    to: 'pages#help' 
  get  '/about',   to: 'pages#about'
  get  '/contact', to: 'pages#contact'
  get  '/signup',  to: 'users#new'
  get  '/users/:id', to: 'users#show', as: 'user'
  get  '/users', to: 'users#index'
  get  '/terms/show'# 登録前の注意事項
  get  '/users/:id/following_posts',to: 'users#following_posts' # フォローの投稿
  post '/follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post '/unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

  resources :notifications, only: :index
  resources :users do
    member do
     get :following, :followers, :following_posts
    end
  end
  resources :relationships,       only: [:create, :destroy]
  
  resources :posts, only: %i(new create index show destroy) do
  resources :photos, only: %i(create)
  resources :users, only: :show
  resources :likes, only: %i(create destroy)
  resources :comments, only: %i(create destroy)
  resources :password_resets, only: [:new, :create, :edit, :update]
  end
  
end

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <%= link_to "K-site", following_posts_user_path(current_user) ,class: "logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-md-auto align-items-center">

      <li>
          <%= link_to "", user_path(current_user), class: "nav-link commonNavIcon profile-icon" %>
      </li>
  
     <li>
    <dl class="searchbox">
    <%= search_form_for @search, url: posts_path do |f| %>
    <dt><%= f.text_field :caption_cont ,placeholder: '検索する投稿を入力...' %></dt>
    <dd><%= f.submit ("検索") , class: 'search-btn'%></dd>
  <% end %>

</dl>
      </li>
    </dl>
        </li>
        
  <li class="notification"><%= link_to '通知', notifications_path, class:"btn"  %>
  <% if unchecked_notifications.any? %>
    <i class="fa fa-circle notification-circle "></i>
  <% end %>

      </ul>
    </div>
  </div>
</nav>