config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  devise_for :users
  
  root 'pages#home'
  get  '/help',    to: 'pages#help' 
  get  '/about',   to: 'pages#about'
  get  '/contact', to: 'pages#contact'
  get  '/signup',  to: 'users#new'
  get  '/users/:id', to: 'users#show', as: 'user'
  get  '/users', to: 'users#index'
  get  '/terms/show'# 登録前の注意事項
  get  '/users/:id/following_posts',to: 'users#following_posts' # フォローの投稿
  post '/follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post '/unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

  resources :notifications, only: :index
  resources :users do
    member do
     get :following, :followers, :following_posts
    end
  end
  resources :relationships,       only: [:create, :destroy]
  
  resources :posts, only: %i(new create index show destroy) do
  resources :photos, only: %i(create)
  resources :users, only: :show
  resources :likes, only: %i(create destroy)
  resources :comments, only: %i(create destroy)
  resources :password_resets, only: [:new, :create, :edit, :update]
  end
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :notifications, dependent: :destroy

  # この行を追加する
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :photos

  def liked_by(current_user)
    # user_idが一致するlikeを検索する
    Like.find_by(user_id: current_user.id, post_id: id)
  end
  
   def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end
  
    def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    # まだ誰もコメントしていない場合は、投稿者に通知を送る
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authenticate_user!
  
  before_action :set_post, only: %i(show destroy)
  
  def new
    @post = Post.new
    @post.photos.build
  end
  
  def create
    @post = Post.new(post_params)
    if @post.photos.present?
      @post.save
      redirect_to post_path(@post.id)
      flash[:notice] = "投稿が保存されました"
    else
      redirect_to new_post_path
      flash[:alert] = "投稿に失敗しました"
    end
  end
  
  
  def index
    @posts = Post.limit(30).includes(:photos, :user).order('created_at DESC')
  end
  
    @post
  def show
  end
  
    @post
  def destroy
    if @post.user == current_user
      flash[:notice] = "投稿が削除されました" if @post.destroy
    else
      flash[:alert] = "投稿の削除に失敗しました"
    end
    redirect_to posts_path
  end

   
  private
    def post_params
      params.require(:post).permit(:caption, photos_attributes: [:image]).merge(user_id: current_user.id)
    end
    
    def set_post
      @post = Post.find_by(id: params[:id])
    end
 
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_list.html.erb
<% post.comments.each do |comment| %>
  <div class="mb-2">
    <% if comment.user == current_user %>
      <%= link_to "", post_comment_path(post.id, comment), method: :delete, remote: true, class: "delete-comment" %>
    <% end %>
    <span>
      <strong>
        <%= link_to comment.user.name, user_path(comment.user), class: "no-text-decoration black-color" %>
      </strong>
    </span>
    <span><%= comment.comment %></span>
  </div>
<% end %>

app/views/posts/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
    <% if likes.size == 1 %>
      <%= like.user.name %> </strong> が「いいね！」しました
    <% elsif like == likes.last %>
      </strong>and<strong>
      <%= + like.user.name %></strong> が「いいね！」しました
    <% elsif index > 1 %>
      </strong><%= "and " + (likes.size-index).to_s + " 他 " %> が「いいね！」しました
      <% break %>
    <% elsif index == likes.size-2 || index == 1 %>
      <%= like.user.name %>
    <% else %>
      <%= like.user.name + ", " %>
    <% end %>
  <% end %>
</strong>

app/views/posts/index.html.erb
<div class="center">
<h1>お気に入りの写真をチェックしよう</h1>
<div class="row">
<% @search_posts.each do |post| %>
 <div class="col-md-4" >
 <div>
 <h6><%= post.caption %></h6>
 <%= link_to post_path(post) do %>
  <%= image_tag post.photos.first.image.url(:medium) %>
<% end %>
</div>
</div>
<% end %>
</div>
</div>

app/views/posts/new.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        投稿画面
      </div>
      <div class="card-body">
        <%= form_with model: @post, class: "upload-images p-0 border-0" do |f| %>
          <div class="form-group row mt-2">
            <div class="col-auto pr-0">
              <%= image_tag avatar_url(current_user), class: "post-profile-icon" %>
            </div>
            <div class="col pl-0">
              <%= f.text_field :caption, class: "form-control border-0", placeholder: "タイトル" %>
            </div>
          </div>
          <div class="mb-3">

            <%= f.fields_for :photos do |i| %>
              <%= i.file_field :image %>
            <% end %>

          </div>
          <%= f.submit "投稿する", class: "btn btn-primary" %>
        <% end %>
        
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="col-md-10 col-md-offset-1 mx-auto postShow-wrap">
  <div class="row post-wrap">
    <div class="col-md-8">
      <div class="card-left">
        <%= image_tag @post.photos.first.image.url(:medium), class: "card-img-top" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card-right">
        <div class="card-right-comment">
          <div class="card-right-name">
            <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
              <%= image_tag avatar_url(@post.user), class: "post-profile-icon" %>
            <% end %>
            <%= link_to user_path(@post.user), class: "black-color no-text-decoration post-user-name",
              title: @post.user.name do %>
              <strong><%= @post.user.name %></strong>
            <% end %>

            <% if @post.user_id == current_user.id %>
              <%= link_to post_path(@post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
                <div class="delete-post-icon">
                </div>
              <% end %>
            <% end %>

          </div>
          <div class="m-2">
            <strong>
              <%= @post.caption %>
            </strong>
          </div>
          <div class="comment-post-id">
            <div class="m-2">

              <div id="comment-post-<%= @post.id.to_s %>">
                <%= render 'comment_list', post: @post %>
              </div>
        
            </div>
          </div>
        </div>
        <div class="row parts">

          <div id="like-icon-post-<%= @post.id.to_s %>">
            <% if @post.liked_by(current_user).present? %>
              <%= link_to "いいねを取り消す", post_like_path(@post.id, @post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
            <% else %>
              <%= link_to "いいね", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text" %>
            <% end %>
          </div>

        </div>

        <div id="like-text-post-<%= @post.id.to_s %>">
          <%= render "like_text", { likes: @post.likes } %>
        </div>

        <div class="post-time"><%= time_ago_in_words(@post.created_at).upcase %>前</div>
        <hr>

        <div class="row parts" id="comment-form-post-<%= @post.id.to_s %>">
          <%= form_with model: [@post, Comment.new],  class: "w-100" do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :post_id, value: @post.id %>
            <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>